---
- name: Install Docker and run container
  hosts: all
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker python package
      pip:
        name: docker
        state: present

    - name: Run Docker container
      docker_container:
        name: snake_game_container
        image: samdroberts/snakejs
        ports:
          - "8081:80"
        state: started
