name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      run: |
        timestamp=$(date +%s)
        docker build . --file Dockerfile --tag samdroberts/snakejs:$timestamp
        docker tag samdroberts/snakejs:$timestamp samdroberts/snakejs:latest
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to Docker Hub
      run: docker push samdroberts/snakejs:latest
